# Use an official Node.js runtime as the base image
FROM node:21

# Set the working directory inside the container
WORKDIR /app

# Remove NPM cache and node_modules
RUN rm -rf /root/.npm /app/node_modules

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your project files to the working directory
COPY . .

# Set environment variable to run tests headlessly
ENV CYPRESS_ENV=ci

# Run the tests when the container starts
CMD [npx cypress run]
